import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ADDONS = ROOT / "CLASH HAL Additions" / "addons"
ADDON = ADDONS / "clash_hal_additions"
CONFIG = ADDON / "config.cpp"


def config() -> str:
    return CONFIG.read_text(encoding="utf-8")


def cfg_functions() -> str:
    source = config()
    return source[source.index("class CfgFunctions"):]


def generated_functions() -> dict:
    """Map each CfgFunctions-generated name (TAG_fnc_class) to its file= path."""
    source = cfg_functions()
    tag = re.search(r'tag\s*=\s*"(\w+)"', source)
    assert tag, "CfgFunctions needs an explicit tag; the class-name default is how this broke"
    functions = re.findall(r'class\s+(\w+)\s*\{\s*file\s*=\s*"([^"]+)"', source)
    assert functions
    return {f"{tag.group(1)}_fnc_{name}": path for name, path in functions}


def test_every_function_the_scripts_call_is_generated_by_the_config():
    generated = generated_functions()
    called = set()
    for script in (ADDON / "functions").glob("*.sqf"):
        called |= set(re.findall(r"\bCLASH_fnc_\w+", script.read_text(encoding="utf-8")))
    assert called, "scripts should reference their own functions"
    missing = called - set(generated)
    assert not missing, f"called but never generated by CfgFunctions: {sorted(missing)}"


def test_every_function_file_is_a_full_path_to_a_file_that_exists():
    # A function-level file= is a full path and ignores any category folder,
    # so a bare "fnc_x.sqf" resolves to nothing inside the PBO.
    for name, path in generated_functions().items():
        assert path.startswith("\\clash_hal_additions\\"), (name, path)
        on_disk = ADDONS.joinpath(*path.lstrip("\\").split("\\"))
        assert on_disk.is_file(), (name, path)


def test_prefix_in_paths_matches_the_addon_folder_that_becomes_the_pbo():
    prefixes = {path.lstrip("\\").split("\\")[0] for path in generated_functions().values()}
    assert prefixes == {ADDON.name}


def test_start_is_the_only_preinit_entry_point():
    source = cfg_functions()
    preinit = re.findall(r'class\s+(\w+)\s*\{[^}]*preInit\s*=\s*1', source)
    assert preinit == ["HALAdd_Start"]


def test_required_version_is_an_engine_version_not_the_nr6_pack_version():
    version = float(re.search(r"requiredVersion\s*=\s*([0-9.]+)", config()).group(1))
    assert version < 3


def test_required_addon_is_nr6_hals_real_cfgpatches_class():
    hal_config = (ROOT / "NR6 Hal" / "addons" / "nr6_hal" / "config.cpp").read_text(encoding="utf-8")
    patches = hal_config[hal_config.index("class CfgPatches"):]
    hal_class = re.search(r"class\s+(\w+)", patches[len("class CfgPatches"):]).group(1)
    assert re.search(rf'requiredAddons\[\]\s*=\s*\{{\s*"{hal_class}"\s*\}}', config())
